### ISSUE TITLE
Recommit the scripts ? 

### ISSUE THREAD

**Issue by supeazn316** [angelsix/youtube#1]
After watching video #2 on WpfTreeView and coming back here to pull some of the cs scripts i noticed that MainWindow.xaml doesn't match the video's version. The other scripts that are different as well. I could edit the scripts but my current code is giving me errors.

**Comment by angelsix** [comment]
There has only ever been one commit to those files. What is different and doesn't work for you? They compile and run fine (just pulled clean repo and test compiled in VS 2017 no problem)

**Comment by supeazn316** [comment]
Error #1 - The name "HeaderToImageConverter" does not exist in the namespace "clr-namespace:WpfTreeView".	Line 22	

Error #2 - Cannot find the static member 'Instanace' on the type 'HeaderToImageConverter'.	 Line 22	
Here is an extract of my HeaderToImageConverter.cs

`HeaderToImageConverter.cs
using System;
using System.Globalization;
using System.IO;
using System.Windows.Data;
using System.Windows.Media.Imaging;

namespace WpfTreeView
{
    /// <summary>
    /// Converts a full path to a specific image type of a drive, folder or file
    /// </summary>
    [ValueConversion(typeof(DirectoryItemType), typeof(BitmapImage))]
    public class HeaderToImageConverter : IValueConverter
    {
        public static HeaderToImageConverter Instance = new HeaderToImageConverter();

        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {            
            // By default, we presume an image
            var image = "Images/file.png";

            switch ((DirectoryItemType)value)
            {
                case DirectoryItemType.Drive:
                    image = "Images/drive.png";
                    break;
                case DirectoryItemType.Folder:
                    image = "Images/folder-closed.png";
                    break;

            }

            //// If the name is blank, we presume it's a drive as we cannot have a blank file or folder name
            //if (string.IsNullOrEmpty(name))
            //    image = "Images/drive.png";
            //else if (new FileInfo(path).Attributes.HasFlag(FileAttributes.Directory))
            //    image = "Images/folder-closed.png";

            return new BitmapImage(new Uri($"pack://application:,,,/{image}"));
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}`

Here is the extract of my Mainwindow.xaml - line 22 is where the program is erroring
`<Window x:Class="WpfTreeView.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfTreeView"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
   <Grid>

        <TreeView x:Name="FolderView" ItemsSource="{Binding Items}">
            <TreeView.ItemContainerStyle>
                <Style TargetType="{x:Type TreeViewItem}">
                    <Setter Property="IsExpanded" Value="{Binding IsExpanded, Mode=TwoWay}" />
                </Style>                
            </TreeView.ItemContainerStyle>

            <TreeView.ItemTemplate>
                <HierarchicalDataTemplate ItemsSource="{Binding Children}">
                    <StackPanel Orientation="Horizontal">
                        <Image Width="20" Margin="3" 
                               Source="{Binding Type, 
                                Converter={x:Static local:HeaderToImageConverter.Instanace}}" />
                        <TextBlock VerticalAlignment="Center" Text="{Binding Name}" />
                    </StackPanel>
                </HierarchicalDataTemplate>
            </TreeView.ItemTemplate>
        </TreeView>
    </Grid>
    </Window>
`

**Comment by supeazn316** [comment]
oh i see the issue. I'm watching video #3 of WPF while trying to code #2 video. D'oh !

**Comment by angelsix** [comment]
You are typing 'Instanace' instead of 'Instance' ?
