### ISSUE TITLE
IsExpanded Binding not working

### ISSUE THREAD

**Issue by nicolasponlet** [angelsix/youtube#3]
Hello Luke,

First of all thank you for your great job. I am trying to learn C# on my own and your videos help me a lot.

However, I would like to use your WpfTreeModel in my application, but the Binding with the IsExpanded property doesn't seem to work. When I expand a drive on the view, the property DirectoryItemViewModel.Children is filled as it would have to be, but the subfolders don't appear on the view.

I've attached my solution. If you could take a look, I would be very gratefull ;-)

Thank you.

[OPCAnalyser.zip](https://github.com/angelsix/youtube/files/1825013/OPCAnalyser.zip)

**Comment by angelsix** [comment]
You are using MvvmLight, whereas I use just WPF itself as it supports view models and MVVM pattern, and Fody Weaver. Your solution won't work because MvvmLight isn't notifying the UI of the change of children. Just do it as I do it in the video. No need for MvvmLight
