### ISSUE TITLE
Slack Dark Theme lost dark color

### ISSUE THREAD

**Issue by Gobluebro** [angelsix/youtube#4]
I have implemented the slack dark theme.

Today I opened slack and the message background is not dark anymore. 

I have attached a file of how it currently looks.
![2018-04-17 08_45_40-slack](https://user-images.githubusercontent.com/14102413/38870435-d1860934-421b-11e8-94e3-ccb09233c0b6.png)

**Comment by angelsix** [comment]
Sorted https://github.com/angelsix/youtube/commit/bb7c1841f920a7a6a7bdf8cfa6b70822bb1d02fd
